package com.makers.makersbnb.controller;

import com.makers.makersbnb.model.Space;
import com.makers.makersbnb.repository.SpaceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.view.RedirectView;

import java.util.List;

// tell Spring Boot this class is a controller
@Controller
public class StaticPageController {
    // tell Spring Boot this method handles the 'GET "/"' request

    @Autowired
    SpaceRepository SpaceRepository;

    @GetMapping("/")
    public ModelAndView landingPage() {
        ModelAndView modelAndView = new ModelAndView("LandingPage");
        // for now, imagine this value was generated by querying the database
        Long nSpaces = SpaceRepository.count();
        Integer nBookings = 123;
        // this next line makes nSpaces available in the template
        modelAndView.addObject("nSpaces", nSpaces);
        modelAndView.addObject("nBookings", nBookings);
        return modelAndView;
    }

    @GetMapping("/contactus")
    public ModelAndView contactUs() {
        return new ModelAndView("ContactUs");
    }

    @GetMapping("/spaces")
    public ModelAndView spaces() {
        ModelAndView modelAndView = new ModelAndView("spaces/spaces");
        Iterable<Space> spaces = SpaceRepository.findAll();
        modelAndView.addObject("spaces", spaces);
        return modelAndView;
    }

    @GetMapping("/spaces/new")
    public ModelAndView newSpaceForm() {
        // this is the space referred to in th:object (look back at the form code)
        Space space = new Space();
        ModelAndView newSpaceForm = new ModelAndView("spaces/New");
        newSpaceForm.addObject("space", space);
        return newSpaceForm;
    }

    @PostMapping("/spaces")
    public RedirectView create(Space space) {
        SpaceRepository.save(space);
        // assumes you already created a method to handle `GET "/spaces"`
        return new RedirectView("/spaces");
    }

//    @PostMapping("/spaces/search")
//    public RedirectView search(String search){
//        SpaceRepository.findSpaceByName(search);
//        return new RedirectView("/");
//    }


}

// the difference boot and bootrun is